### ISSUE TITLE
Cannot access Logger class with Datadog.Logger

### ISSUE THREAD

**Issue by amyslies** [DataDog/dd-sdk-ios#142] opened 2020-06-16 18:22 UTC
With our own Logger class in Logger.swift, we can't access Datadog's Logger class with Datadog.Logger.

Already tried building a logger by doing the following:
```
import Datadog
import Datadog.Logger
import Datadog.Datadog
...

Datadog.Logger.builder... // still doesn't work

```

**Comment by ncreated** [comment] 2020-06-17 05:49
Hello @amyslies 👋. This seems to be duplicate of #127. Until we fix it, could you please try the workaround and create a separate `.swift` file that only imports `Datadog` and defines `typealias DatadogLogger = Logger`?

```swift
// DatadogLoggerAlias.swift

import class Datadog.Logger

typealias DatadogLogger = Logger
```

Then you should be good to go with `DatadogLogger.builder` instead of `Datadog.Logger.builder`.

Let me know if it helps 🙂.

**Comment by ncreated** [comment] 2020-08-03 13:39
`DDLogger` typealias was added in [`1.3.0`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.3.0).

**Closed by ncreated** 2020-08-03 13:39 UTC
Labels: duplicate
