### ISSUE TITLE
CocoaPods  Error  Module  'DatadogObjc" Not Found

### ISSUE THREAD

**Issue by ajeyasriharsha-v** [DataDog/dd-sdk-ios#1115] opened 2023-01-06 07:27 UTC
### The issue

📝 Give us the error message you receive, describe the problem and answer the questions.

Able to Compile Succesfully on Xcode 13.2 However the same Project is unable to Build in Xcode 13.4.1 and Above even tried with the Latest Xcode version But Unable to compile and See the Error: Module  'DatadogObjc" Not Found

Note:The Current project which we are working is purely an Objective c Project 

Attaching the Messages from the Build on both the Xcode versions if that can help 
[Xcode_13.2.txt](https://github.com/DataDog/dd-sdk-ios/files/10358122/Xcode_13.2.txt)
[Xcode14.2.txt](https://github.com/DataDog/dd-sdk-ios/files/10358130/Xcode14.2.txt)

#### Datadog SDK version:

_Which version of the Datadog SDK causes this problem? 1.12.1

#### Last working Datadog SDK version:1.11.0

_What is the last Datadog SDK version where this problem didn't occur? 

#### Dependency Manager:

_Which dependency manager do you use? :Cocoapods

#### macOS version: `macOS Monterey 12.6.1 (21G217))`
[Xcode14.2.txt](https://github.com/DataDog/dd-sdk-ios/files/10358125/Xcode14.2.txt)

**Comment by ajeyasriharsha-v** [comment] 2023-01-06 07:29
Attaching the Xcode Screenshot with the Comiplation Error.
<img width="1647" alt="Screenshot 2023-01-06 at 12 56 00 PM" src="https://user-images.githubusercontent.com/113586263/210952040-da35d3b5-7844-4015-889e-6677cd5540e4.png">

**Comment by ajeyasriharsha-v** [comment] 2023-01-06 07:32
In addition to the above provided details i am using the Cocoapods to Integrate with the current Xcworkspace and attaching the podfile also for the reference
[Podfile.pdf](https://github.com/DataDog/dd-sdk-ios/files/10358346/Podfile.pdf)

**Comment by ncreated** [comment] 2023-01-17 09:11
Hello @ajeyasriharsha-v 👋. I referred to your information and made a fresh new Objective-c project with DD SDK setup using Cocoapods. Everything works fine, so the problem seems to be in your configuration, rather than in `dd-sdk-ios`.

Steps I did follow:
* create new Xcode app project (`GH1115`): 100% Objective-C, iOS 12.0 deployment target
* do `pod init` and configure following minimal `Podfile`:
```
target 'GH1115' do
  use_frameworks!

  pod 'DatadogSDKObjc'
  pod 'DatadogSDKCrashReporting'
end
```
* run `pod install`
* call Datadog SDK in `AppDelegate.m`:
```objective-c
// import DD SDK with crash reporting:
@import DatadogObjc;
@import DatadogCrashReporting;

// call SDK APIs to make sure it works:
[DDDatadog setVerbosityLevel:DDSDKVerbosityLevelDebug];
[DDCrashReportingPlugin new];
```

With above setup the build succeeds ✅, so everything is fine in our SDK.

---

When looking into your `Xcode14.2.txt` log, I can see multiple arch-related errors emitted for other different dependencies (not only Datadog):
```
❌  /Users/(...)/DataDogAnalyticsService.m:11:9: module 'DatadogObjc' not found

❌  fatal error: lipo: /Users/(...)/AuthModule.framework/AuthModule have the same architectures (arm64) and can't be in the same fat output file

❌  fatal error: lipo: /Users/(...)/AuthModule.framework/AuthModule have the same architectures (arm64) and can't be in the same fat output file
```

Also, in your `Podfile` I can see that you're explicitly exluding `arm64` slice from all libs:
```
config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
```
so it can't work on iOS simulator on M1 as M1 requires `arm64` slice 🙂. That leads me to the conclusion that problem is indeed in your configuration and we can't help much on this.

I will close this issue for now, but feel free to reopen it with providing reproduction steps for this issue in minimal new Xcode project.

**Closed by ncreated** 2023-01-17 09:11 UTC
Labels: compilation issue
