### ISSUE TITLE
Datadog v2.0.0 not sending data to the dashboard

### ISSUE THREAD

**Issue by lpbas** [DataDog/dd-sdk-ios#1426] opened 2023-08-18 14:23 UTC
### The thing

We're trying to integrate Datadog in our mobile app and while we were using the SDK `v1.X.X` we were able to receive data on our Datadog dashboard.

After migrating to the SDK `v2.0.0`, the SDK gets initialised properly but no RUM or crash report data get reported to our dashboard.

We've enabled debug logging but the only log we are seeing from the SDK are:
```
[DATADOG SDK] 🐶 → 17:12:19.001 No pending crash available
[DATADOG SDK] 🐶 → 16:52:17.109 NTP time synchronization completed.
```
Our setup is the following in our AppDelegate called in `application(didFinishLaunchingWithOptions:)`:

```swift
func setupDatadog() {
    // Initialize Datadog Core 🐶
    print("Datadog: 1 isInitialized: \(Datadog.isInitialized())") // prints false
    
    Datadog.initialize(
      with: Datadog.Configuration(
        clientToken: Constants.Datadog.clientToken,
        env: Constants.Datadog.environment,
        site: .us1,
        service: Constants.Datadog.service
      ),
      trackingConsent: .granted // TODO: - Add proper consent gathering
    )
    
    runOnlyInDebug {
        Datadog.verbosityLevel = .debug
    }
    print("Datadog: 2 isInitialized: \(Datadog.isInitialized())") // prints true
    
    // Initialize Datadog RUM 🍹
    let urlSessionTrackingConfig = RUM.Configuration.URLSessionTracking(firstPartyHostsTracing: RUM.Configuration.URLSessionTracking.FirstPartyHostsTracing.trace(hosts: Constants.Datadog.hosts))
    RUM.enable(
      with: RUM.Configuration(
        applicationID: Constants.Datadog.appID,
        uiKitViewsPredicate: DefaultUIKitRUMViewsPredicate(),
        uiKitActionsPredicate: DefaultUIKitRUMActionsPredicate(),
        urlSessionTracking: urlSessionTrackingConfig,
        trackBackgroundEvents: true
      )
    )
    print("Datadog: 3 isInitialized: \(Datadog.isInitialized())") // prints true
    
    // Initialize Datadog crash reporting 💥
    CrashReporting.enable()
    
    // Enable Logs and Traces for testing the SDK
    Logs.enable(with: Logs.Configuration())
    
    let tracingConfig = Trace.Configuration.URLSessionTracking(firstPartyHostsTracing: .trace(hosts: Constants.Datadog.hosts))

    // The next line prints a warning that Trace.enable must be called after initializing the Datadog SDK.
    Trace.enable(with: Trace.Configuration(urlSessionTracking: tracingConfig, bundleWithRumEnabled: true, networkInfoEnabled: true))
    print("Datadog: 4 isInitialized: \(Datadog.isInitialized())") // prints true
}
```

Is there a way to debug why the RUM data are not being sent to the Datadog dashboard?

**Comment by ncreated** [comment] 2023-08-23 15:49
Hey @lpbas 👋. I tried this exact setup in a new project using `2.0.0` and it works fine. Also, I'm not seeing the _"Trace.enable() must be called after initializing the Datatdog SDK"_ warning is vanilla project, which suggests that something could be wrong in your surrounding setup.

Normally with `Datadog.verbosityLevel = .debug`, you should see logs similar to following (be patient, uploaders may start 10s of seconds after app is launched):
```
[DATADOG SDK] 🐶 → 17:40:05.835 💡 (tracing) No upload. Batch to upload: NO, System conditions: ✅
[DATADOG SDK] 🐶 → 17:40:05.837 ⏳ (rum) Uploading batch...
[DATADOG SDK] 🐶 → 17:40:05.836 💡 (logging) No upload. Batch to upload: NO, System conditions: ✅
[DATADOG SDK] 🐶 → 17:40:06.424    → (rum) accepted, won't be retransmitted: [response code: 202 (accepted), request ID: A2E2BC52-BA3C-459D-9B74-D3B5FC635635]
```

For slightly more debugging options, you may also try:
* `RUMMonitor.shared().debug = true` to debug the current RUM view set up in the app;
* pass `DD_DEBUG` argument on application launch, to elevate sample rates and make uploads a bit faster;

<img width="776" alt="Screenshot 2023-08-23 at 17 45 31" src="https://github.com/DataDog/dd-sdk-ios/assets/2358722/1147f345-6c9c-49e4-b408-2326c692800a">

**Comment by lpbas** [comment] 2023-10-12 14:03
Thank you for your response @ncreated and sorry for my delayed answer, I now found the time to resume working on our Datadog 2.0 integration.

I created a clean project that only contained our Datadog initialisation code and a simple view and we are indeed receiving both RUM data and crash reports.

However, in our actual project, I'm still not seeing any data on the dashboard, nor do I get the console messages that the RUM batch has been uploaded.

I believe there must be an issue with the way we are integrating Datadog into our project, since we are using tuist to manage our xcode project and dependencies (which uses SPM under the hood), since I'm seeing the following logs in the debug console, pointing to a conflict between the `DatadogRUM` and `DatadogCrashReporting` frameworks.

Also, while call `RUM.enable(...)` and the breakpoints inside the Datadog framework indicate that the SDK is initialised successfully, we still get the following error when we try to run `RUMMonitor.shared().debug = true` at the very end of our initialisation function:
`🔥 Datadog SDK usage error: RUM feature must be enabled before calling RUMMonitor.shared(in:).`

I will try tomorrow removing the Datadog SDK from the tuist dependencies and try adding it as a normal SPM dependency so we can pinpoint if the issue is with Datadog and tuist or not and report back.

[datadog_2.0_debug_logs.txt](https://github.com/DataDog/dd-sdk-ios/files/12883271/datadog_2.0_debug_logs.txt)

**Comment by ncreated** [comment] 2023-12-11 09:43
Hey @lpbas 👋. Thanks for keeping us up to date. I'm glad to hear it works for you with bare SPM setup which indicates no problem on our side. For that reason I'll close this issue.

> the following logs in the debug console, pointing to a conflict between the DatadogRUM and DatadogCrashReporting frameworks

Yes, this might be a possible root cause. You need to verify your [Tuist](https://github.com/tuist/tuist) setup and avoid duplicating libraries. Unfortunately, this isn't something we can assist you on.

**Closed by ncreated** 2023-12-11 09:43 UTC
Labels: awaiting response
