### ISSUE TITLE
DataDog sdk crash in `com.datadoghq.ios-sdk-logging-upload`

### ISSUE THREAD

**Issue by sumit-vts** [DataDog/dd-sdk-ios#835] opened 2022-05-02 10:57 UTC
### The crash

📝 Give us the crash report or stack trace, describe the problem in details and answer the questions.
```
Crash stack:
Crashed: com.datadoghq.ios-sdk-logging-upload
0  libobjc.A.dylib                0x430c object_getClass + 8
1  ???                            0x11b348044 (Missing)
2  ???                            0x11b3449e8 (Missing)
3  ???                            0x11b42a818 (Missing)
4  ???                            0x11b42a510 (Missing)
5  ???                            0x11b42a464 (Missing)
6  ???                            0x11b47a024 (Missing)
7  ???                            0x11b47af2c (Missing)
8  ???                            0x11b47af2c (Missing)
9  ???                            0x11b479d2c (Missing)
10 ???                            0x11b427af8 (Missing)
11 ???                            0x11b427bf4 (Missing)
12 ???                            0x11b4388e8 (Missing)
13 ???                            0x11b3d6f24 (Missing)
14 ???                            0x11c5c0178 (Missing)
15 Datadog                        0x7d5a8 $s7Datadog12MobileDeviceC02uiC011processInfo18notificationCenterACSo8UIDeviceC_So09NSProcessF0CSo014NSNotificationH0CtcfcAC13BatteryStatusVycfU1_TA + 44
16 Datadog                        0x3b7cc $s7Datadog20DataUploadConditionsV011blockersForC0SayAC7BlockerOGyF + 88
17 Datadog                        0x3cfec $s7Datadog16DataUploadWorkerC5queue10fileReader12dataUploader16uploadConditions5delay11featureName15internalMonitorACSo012OS_dispatch_E0C_AA0G0_pAA0bI4Type_pAA0bcK0VAA5Delay_pSSAA08InternalP0VSgtcfcyycfU_ + 148
18 Datadog                        0x761ec $sIeg_IeyB_TR + 20
19 libdispatch.dylib              0x3edd0 _dispatch_block_async_invoke2 + 104
20 libdispatch.dylib              0x5b524 _dispatch_client_callout + 16
21 libdispatch.dylib              0x35274 _dispatch_continuation_pop$VARIANT$armv81 + 404
22 libdispatch.dylib              0x45410 _dispatch_source_invoke$VARIANT$armv81 + 1220
23 libdispatch.dylib              0x38a0c _dispatch_lane_serial_drain$VARIANT$armv81 + 260
24 libdispatch.dylib              0x3954c _dispatch_lane_invoke$VARIANT$armv81 + 396
25 libdispatch.dylib              0x4284c _dispatch_workloop_worker_thread + 580
26 libsystem_pthread.dylib        0xbb74 _pthread_wqthread + 272
27 libsystem_pthread.dylib        0xe740 start_wqthread + 8
---
```
#### Datadog SDK versions:

_Which version(s) of the Datadog SDK you see this crash happening in?_ 
1.9.0
#### Last stable Datadog SDK version: 

_What is the last Datadog SDK version where this crash doesn't happen?_ 

#### Volume:

_What % of your app sessions is impacted with this crash? 
#### OS version:

_Which iOS versions does this crash happen on?_ 
 13.7.0

#### Deployment Target:

_What is the Deployment Target of your app? 

`iOS 12`, `iPhone` + `iPad`

#### Device version:

_Which devices does this crash happen on? e.g. `iPhone X` only or various iPads_ 

iPhone 8 with iOS version 13.7.0

#### Environment:

_Do you notice any environment correlation in crash reports? e.g. low battery, no internet connection, memory pressure_

NO

**Comment by maxep** [comment] 2022-05-05 07:44
Hi @sumit-vts 

The missing frames `??? ... (Missing)` in the stack trace are hiding important information about the crash, are you able to provide more information?

Thank you!

**Comment by sumit-vts** [comment] 2022-05-31 13:58
NO maxep

**Comment by maxep** [comment] 2022-06-16 14:31
Hi @sumit-vts,

we suspect that this is a duplicate of #609 which originate from an Apple issue tracked in this radar ticket: [FB9741207](https://openradar.appspot.com/FB9741207).

I'm closing this issue, but feel free to add more details to #609

**Closed by maxep** 2022-06-16 14:31 UTC
Labels: awaiting response, crash
