### ISSUE TITLE
[Xcode 15 + Cocoapods] Crash on `NWPathMonitor*`

### ISSUE THREAD

**Issue by lukas-koblmueller** [DataDog/dd-sdk-ios#1509] opened 2023-10-05 10:13 UTC
### The crash

Only happens when building with Xcode15 when using Cocoapods:

DatadogCore crashes on line #374 
```swift
subscribe(\.networkConnectionInfo, to: NWPathMonitorPublisher())
``` 
with the following error:
```
Thread 8: EXC_BAD_ACCESS (code=1, address=0x0)
```
immediately after app start.

When seettings the minimum iOS deployment target to 12+ instead of 11+ it works.
We believe this is because of `NWPathMonitor` crashing on iOS11 as its not supported anymore.
 
---

#### Datadog SDK versions:

2.1.2, but also reproducible with 2.2.1.
2.3.0 throws a different error (unknown symbol called), but also crashes.

#### Last stable Datadog SDK version:

not sure

#### Volume:

100%, immediate crash

#### Deployment Target:

iOS11

![Screenshot 2023-10-05 at 12 07 13](https://github.com/DataDog/dd-sdk-ios/assets/27801945/423ea339-5d0f-4ead-888e-6cbd270ba4ab)

**Comment by maciejburda** [comment] 2023-10-06 11:03
Thanks for reporting @lukas-koblmueller !

We acknowledge the problem and we'll try to resolve it as soon as possible.
In the meantime you can try using this snippet to automatically change the deployment target of Datadog dependencies in the `Podfile`:

```
ios11Targets = [
  'DatadogCore',
  'DatadogRUM',
  '...'
]

post_install do |installer|   
  installer.pods_project.targets.each do |target|
    # Bump minimum deployment version
    if ios11Targets.include?(target.name)
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
```

Please make sure you updated ios11Targets with the Datadog modules in use.

**Comment by netbe** [comment] 2023-10-09 15:30
So this happened to us too on 1.22.0. Crash on iOS 15,16 but not on iOS 17. 

Using Carthage, bumping the IPHONEOS_DEPLOYMENT_TARGET to 12.0 and recompile fixed the issue.

**Comment by ncreated** [comment] 2023-10-17 10:31
👋 I managed to reproduce this problem in pure Xcode project without using Datadog SDK. This leads to a conclusion that we're dealing with Xcode / Apple problem, not an issue in Datadog SDK. [This thread on Apple forum](https://developer.apple.com/forums/thread/737672) is 100% related so I updated it with more context. I also filled-in 🐞 bug report to Apple: [**FB13278576**](https://openradar.appspot.com/FB13278576).

I described the full context of this problem below, with highlighting the workaround for Cocoapods users. Because there is nothing we can do with this issue, I'll close it as addressed, but keep pinned for visibility.

### Full Context
If your app supports iOS 11, **be aware that  Xcode 15 drops the iOS 11 deployment target**. You must bump it to iOS 12 for all targets, otherwise you'll get following build warning:
> The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.0.99.

Now:
- If you ignore this warning, the app built with Xcode 15 will crash on pre-iOS 17.0 device if you make any use of Apple's [Network](https://developer.apple.com/documentation/network) framework in iOS 11 target (that includes any of your 3rd-party dependencies like Datadog iOS SDK). We believe that ignored warning should not lead to crash, hence we reported this as bug to Apple: [FB13278576](https://openradar.appspot.com/FB13278576).

- If you use Xcode 15 and see no warning because `IPHONEOS_DEPLOYMENT_TARGET` is higher or equal 12 in all your targets (and 3rd party targets) that use [Network](https://developer.apple.com/documentation/network), then everything should be fine.

Datadog iOS SDK is impacted by this problem because we leverage Apple's [Network](https://developer.apple.com/documentation/network) framework and today we still support iOS 11. If you use Cocoapods, you may need to patch Datadog pods using the `post_install` script listed below.

### Impact on Cocoapods users who use Xcode 15

Cocoapods makes the situation complicated because it compiles 3rd party dependencies into pod targets for you. If any dependency declares `ios.deployment_target = '11.0'` then it must be patched using the post install script. I updated the one originally proposed by @maciejburda to be more generic (bump deployment target in all pods, not only Datadog):
```ruby
post_install do |installer|   
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '11.0'
        print '[i] Adjusting IPHONEOS_DEPLOYMENT_TARGET to 12.0 in '+ target.name + ':' + config.name + "\n"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end 
    end
  end
end
```

### No impact on SPM or Carthage users who use Xcode 15

I haven't observed any extra complications in SPM or Carthage. Static libraries produced by SPM respect the deployment target configured for the whole project and XCFrameworks we provide for Carthage are built with Xcode 14. As long as your project compiles with no `IPHONEOS_DEPLOYMENT_TARGET`-related warning in Xcode 15, it should be fine.

---

### Q: Can this be fixed in Datadog SDK?

A: Unfortunately, no. There is no practical fix to `*.podspec` that we can apply on our side. Today, [app submissions can be done with Xcode 14.1](https://developer.apple.com/news/?id=jd9wcyov), hence Datadog iOS SDK [remains compatible with that version](https://github.com/DataDog/dd-sdk-ios/blob/develop/SUPPORTED-VERSIONS.md#xcode) and offers support to iOS 11. Bumping our deployment target to iOS 12 might be backward-compatible operation only after Xcode 15 becomes the minimal required version by Apple.

**Closed** 2023-10-17 10:34 UTC
Labels: crash
