### ISSUE TITLE
Network Tracing with swizzling

### ISSUE THREAD

**Issue by MarvinNazari** [DataDog/dd-sdk-ios#1642] opened 2024-01-22 09:00 UTC
It seems like that our requests are not being traced when using `URLSession.data(for request: URLRequest, delegate: (URLSessionTaskDelegate)? = nil) async throws -> (Data, URLResponse)`. This is how our setup is done.

``` swift
final class DatadogSessionDataDelegate: NSObject, URLSessionDataDelegate {}

RUM.enable(
    with: RUM.Configuration(
        applicationID: appID,
        urlSessionTracking: .init(firstPartyHostsTracing: .trace(hosts: networkHosts))
    )
)

Trace.enable(
    with: Trace.Configuration(
        urlSessionTracking: .init(
            firstPartyHostsTracing: .trace(
                hosts: networkHosts,
                sampleRate: 100
            )
        ),
        networkInfoEnabled: true
    )
)

URLSessionInstrumentation.enable(
    with: .init(delegateClass: DatadogSessionDataDelegate.self)
)
```

And then when sending our requests, we are using a custom network instrumentation for our own debugging.

```swift
let urlSession = URLSession(
    configuration: .default,
    delegate: DatadogSessionDataDelegate(), // <---- THIS IS THE CLASS THAT DATADOG IS TRACING
    delegateQueue: nil
)

// This is our metrics collector.
private class URLSessionTaskMetricsCollecter: NSObject, URLSessionDataDelegate {
    var metrics: URLSessionTaskMetrics?
    var currentRequest: URLRequest?
    
    func urlSession(_ session: URLSession, task: URLSessionTask, didFinishCollecting metrics: URLSessionTaskMetrics) {
        self.currentRequest = task.currentRequest
        self.metrics = metrics
    }
}

let metricsCollecter = URLSessionTaskMetricsCollecter()
let (rawData, urlResponse) = try await urlSession.data(for: urlRequest, delegate: metricsCollecter)
```

How is the preferred way of handling this?

**Comment by ganeshnj** [comment] 2024-01-22 16:11
Hey @MarvinNazari ,

It looks like you are not enabling the network instrumentation from your setup.

This is perfect
```swift
RUM.enable(
    with: RUM.Configuration(
        applicationID: appID,
        urlSessionTracking: .init(firstPartyHostsTracing: .trace(hosts: networkHosts))
    )
)

Trace.enable(
    with: Trace.Configuration(
        urlSessionTracking: .init(
            firstPartyHostsTracing: .trace(
                hosts: networkHosts,
                sampleRate: 100
            )
        ),
        networkInfoEnabled: true
    )
)
```

Next you must enable the instrumentation on your delegate type which you are passing in the URLSession APIs.

```swift
URLSessionInstrumentation.enable(
    with: .init(
        delegateClass: URLSessionTaskMetricsCollecter.self
    )
)
```

> Remember here the delegate class is the one you are using for your URLSession.

We have also covered this in our docs https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios/?tab=swift#automatically-track-network-requests

Let me know if docs are clear enough.

**Comment by MarvinNazari** [comment] 2024-01-23 08:41
Hey @ganeshnj, I think you are misunderstanding, I have 2 delegate types. One is being set as a delegate when creating the `URLSession()` (this is the delegate that is created for Datadog which is enabled for `URLSessionInstrumentation`). The second delegate I have an another delegate that is being set for a specific URLSessionTask that is being created. when sending request. What I have noticed when sending a request with a specific delegate is that, the delegate that URLSession was created with is not getting called. If that can't be supported then we need a way to instrument our requests without swizzling.

**Comment by ganeshnj** [comment] 2024-01-23 08:47
That's an interesting use case and probably we have not never accounted for.

Can you check and share findings what happens when you enable `URLSessionInstrumentation` on both delegates?

Also, I'm curious on the default behavior when both delegates are provided in a vanilla setup and how these delegate methods are called.

**Comment by ganeshnj** [comment] 2024-01-24 12:44
I did some more tests and it seems it is working as expected.

with following setup 
```swift
class URLTaskDelegate: NSObject, URLSessionTaskDelegate, URLSessionDataDelegate {
    func urlSession(_ session: URLSession, task: URLSessionTask, didFinishCollecting metrics: URLSessionTaskMetrics) {
        print("URLTaskDelegate: didFinishCollecting")
    }
}

class SessionDelegate: NSObject, URLSessionTaskDelegate, URLSessionDataDelegate {
    func urlSession(_ session: URLSession, task: URLSessionTask, didFinishCollecting metrics: URLSessionTaskMetrics) {
        print("SessionDelegate: didFinishCollecting")
    }
}

let sessionDelegate = SessionDelegate()
let session =  URLSession(
      configuration: URLSessionConfiguration.default,
      delegate: sessionDelegate,
      delegateQueue: nil)

let taskDelegate = URLTaskDelegate()

let request = URLRequest(url: URL(string: "https://httpbin.org/get")!)
let (data, response) = try! await session.data(for: request, delegate: taskDelegate)
let httpResponse = response as! HTTPURLResponse
print(httpResponse.statusCode)
// json response
let json = try! JSONSerialization.jsonObject(with: data, options: [])
print(json)
```
stdout
```
URLTaskDelegate: didFinishCollecting
200
...
```

The delegate passed on the `session.data` (or any API that accept it) takes the precedence over the delegate passed during the `URLSession`.

Removing the task delegate would call the session delegate.

```swift 
let (data, response) = try! await session.data(for: request)
```
stdout
```
SessionDelegate: didFinishCollecting
200
...
```

This holds true when the `URLSessionInstrumentation` is enabled. Just for more context, when we swizzle any method, it is always additive, ie the original implementation is always called after the inserted logic.

**Comment by ganeshnj** [comment] 2024-01-26 11:16
Closing it as expected behavior.

**Closed by ganeshnj** 2024-01-26 11:16 UTC
Labels: invalid, awaiting response
