### ISSUE TITLE
Xcode 15 beta 4 - Null objc class data for '_OBJC_METACLASS_$_PLCrashHostInfo'

### ISSUE THREAD

**Issue by EvanGregg** [DataDog/dd-sdk-ios#1385] opened 2023-07-21 11:49 UTC
### The issue

When building on Xcode 15 beta 4, I receive the following link error:
Null objc class data for '_OBJC_METACLASS_$_PLCrashHostInfo' in '/Users/evan/Library/Developer/Xcode/DerivedData/My_Utilita-didldflptfenghfkbrquverumlym/Build/Products/Debug-iphonesimulator/CrashReporter.o'
 

---

#### Datadog SDK version:
We were originally using 1.14, I updated to 1.22 but problem still occurs.

#### Last working Datadog SDK version:

I don't think it is due to a change in Datadog as such, but Xcode checking something new.
I believe there is a new linker with Xcode 15, but that may be unrelated.

#### Dependency Manager:

SPM

#### Other toolset:

Just Xcode and built in SPM

#### Xcode version:

Xcode Version 15.0 beta 4 (15A5195m)

#### Swift version:

Whatever the version with xcode 15 is

#### Deployment Target:

Minimum deployment target is iOS 14

#### macOS version:

13.4.1 (c) (22F770820d)

**Comment by ganeshnj** [comment] 2023-07-21 11:58
Thanks for filing the issue @EvanGregg. I have seen this issue in past with V2 version of the SDK.

However, I just tested with V1 (1.22.0) with Xcode beta 4 and it seems we have this issue here as well. We are investigating the root cause. Stay tuned.

<img width="1137" alt="image" src="https://github.com/DataDog/dd-sdk-ios/assets/8882380/7d9392a1-51be-40d0-a8e3-8f773fbd6908">

**Comment by EvanGregg** [comment] 2023-07-21 12:29
@ganeshnj Thank you for your quick response.
I have tried other linker flag of -ld64 and that does indeed allow us to build again with Xcode 15.

**Comment by ncreated** [comment] 2023-12-11 09:47
Quoting [this comment](https://github.com/microsoft/plcrashreporter/issues/284#issuecomment-1653123826), the problem should be already fixed in Xcode 15 (GA). I'm closing this thread, but feel free to reopen it if issue persists.

**Closed by ncreated** 2023-12-11 09:47 UTC
Labels: compilation issue
