### ISSUE TITLE
Xcode Cloud + Bitcode Issues

### ISSUE THREAD

**Issue by dcilia** [DataDog/dd-sdk-ios#624] opened 2021-10-05 14:24 UTC
### The issue

Integrating with Xcode 13 / SPM

When integrating the sdk in an app that uses Xcode Cloud, there are two issues with the archival / Testflight submission process that is done by Xcode Cloud:

1. Bundle identifier mismatch with Datadog SPM Swift
2. Error occurs in app thinning / bitcode process, Apple references[ Tech Note 2432](https://developer.apple.com/library/archive/technotes/tn2432/_index.html)

---

#### Datadog SDK version:

_Which version of the Datadog SDK causes this problem? e.g. `1.7.0`_

#### Last working Datadog SDK version:

None

#### Dependency Manager:

SPM

#### Other toolset:

Xcode Cloud

#### Xcode version:

Xcode 13

#### Swift version:

5.5

#### Deployment Target:

iOS 14.0

#### macOS version:

N/A

**Comment by ncreated** [comment] 2021-10-06 12:36
Hey @dcilia , thanks for details 👋. Before we dig further, we need some more info:

> 1. Bundle identifier mismatch with Datadog SPM Swift

* What is the exact error message for this? I'm wondering of what kind of match does Xcode Cloud expect.

> 2. Error occurs in app thinning / bitcode process

* What's the error exactly saying?
* What is your "Enable Bitcode" setup for each target (especially the one you use for archiving)?

<img width="483" alt="Screenshot 2021-10-06 at 14 32 42" src="https://user-images.githubusercontent.com/2358722/136203318-101610aa-7e50-4936-bd8f-75d42b965f94.png">

**Comment by lanserxt** [comment] 2021-10-11 06:24
@ncreated Hi! Have faced the asme issues with original Xcode (Version 13.0 (13A233))

**Comment by buranmert** [comment] 2021-11-09 09:44
hey @lanserxt 👋 
does the issue still persist?

**Comment by floriangbh** [comment] 2021-11-10 14:15
I'v just had the same issue this morning : 
<img width="988" alt="Screenshot 2021-11-10 at 15 10 47" src="https://user-images.githubusercontent.com/14054997/141128695-43f1f901-3510-4ed7-8ef0-04f9a82154ce.png">

With Datadog SDK v1.7.2, Datadog SDK is with "Embed & Sign" option with SPM

**Comment by lanserxt** [comment] 2021-11-11 07:14
Hi @buranmert ! 

Sorry, checked just now. Still persists. The same error that @floriangbh have.

**Comment by flipbosch** [comment] 2021-11-11 20:44
Hi, 

We have the same problem when we try to Archive on **Xcode cloud**. Building is working. But Archiving is giving the same error: 

<img width="664" alt="image" src="https://user-images.githubusercontent.com/10187190/141366272-88bb95fe-43e2-48db-9e19-2dfabbc0f5a0.png">

**Comment by buranmert** [comment] 2021-11-12 10:41
unfortunately, i can't reproduce `Invalid Code Signature Identifier`.
but i found [this thread from Apple Dev Forums](https://developer.apple.com/forums/thread/689907): can you please try `DatadogStatic` target in `dd-sdk-ios` package (instead of `Datadog` target which is `.dynamic`) in your projects?

**Comment by dcilia** [comment] 2021-11-12 11:58
Hi, using static version of Datadog will cause bitcode not to work.  The error goes away though.

**Comment by buranmert** [comment] 2021-11-12 14:02
hey again @dcilia 👋 

[from Tech Note 2432](https://developer.apple.com/library/archive/technotes/tn2432/_index.html):

> Static libraries included in an app bundle cause failures
> 
> Static libraries should be linked into your app but not copied into the app bundle. Workaround: Verify that your app does not mistakenly include static libraries

can you look inside your app bundle?

**Comment by dcilia** [comment] 2021-11-12 15:38
> hey again @dcilia 👋
> 
> [from Tech Note 2432](https://developer.apple.com/library/archive/technotes/tn2432/_index.html):
> 
> > Static libraries included in an app bundle cause failures
> > Static libraries should be linked into your app but not copied into the app bundle. Workaround: Verify that your app does not mistakenly include static libraries
> 
> can you look inside your app bundle?

Sure, I can spend some time looking into this, will report back what I find.

**Comment by flipbosch** [comment] 2021-11-14 09:30
@buranmert I tried with below and for me this is solving the issue with `Archiving the app on Xcode Cloud`.

> unfortunately, i can't reproduce `Invalid Code Signature Identifier`.
> but i found [this thread from Apple Dev Forums](https://developer.apple.com/forums/thread/689907): can you please try `DatadogStatic` target in `dd-sdk-ios` package (instead of `Datadog` target which is `.dynamic`) in your projects?

After changing it to static in SPM its compiling and submitted to testflight without any problems. 
Thx! Hope for others it will work aswel.

![image](https://user-images.githubusercontent.com/10187190/141675426-99198f2b-e724-4990-964c-6511e6d03baa.png)

**Comment by buranmert** [comment] 2021-11-24 10:20
the issue seems to be resolved.
i'm closing it now but feel free to reopen if it arises again.

**Comment by Kaspik** [comment] 2022-01-22 23:37
Not sure if this should be closed. The XCode Cloud issue still persist, there is just temporary workaround to use static version. I believe this should be reopen so people like me can find it easier in the future until the Dynamic version is reworked. I believe it's the same issue as https://github.com/DataDog/dd-sdk-ios/issues/250 and similar.

**Comment by jostster** [comment] 2022-04-26 17:17
I think this might be resolved with Xcode 13.3.1? Can anyone confirm?

**Comment by pf-AliKemal** [comment] 2022-05-30 17:58
@buranmert  This issue was fixed with DatadogStatic. instead of Datadog. But I think DatadogStatic repository is removed. 

https://github.com/DatadogStatic/dd-sdk-ios.git getting 404.

Is it removed or moved ?

**Comment by ncreated** [comment] 2022-05-31 08:57
> Is it removed or moved to different source ?

Hey @pf-AliKemal 👋. `DatadogStatic` library is shipped through the same `Package.swift` as `Datadog`, see our [Package.swift](https://github.com/DataDog/dd-sdk-ios/blob/e2a961ddc9439e523cf234829bd9a27a4d79451d/Package.swift#L23). You should see it when using https://github.com/DataDog/dd-sdk-ios in SPM. It was always like this 🙂.

**Comment by pf-AliKemal** [comment] 2022-05-31 09:02
@ncreated  ok cool. now it is working as expected thanks 👍

**Comment by kylebrowning** [comment] 2022-07-28 15:41
Using DataDogStatic is not a foolproof fix because it breaks SwiftUI Previews. 

Is there no solution to getting either DataDog to be dynamic, or fixing SwiftUI previews for DatadogStatic?

**Comment by smadsenjc** [comment] 2022-08-26 14:30
+1 to the above; using `DatadogStatic` isn't an option for those of us using `DatadogCrashReporting`, either. While `DatadogCrashReporting` is a static library, it depends on `Datadog`, a dynamic library, and there isn't another option to get the crash reporting functionality with a static version of the Datadog library.

**Comment by kylebrowning** [comment] 2022-08-26 14:32
Just an FYI Xcode 14 does not fix this issue either.

**Comment by smadsenjc** [comment] 2022-08-26 14:45
What is the history behind explicitly offering both dynamic and static versions of the library, versus letting SPM and the build system handle it? Searches elsewhere consistently point to using `.dynamic` as a problem with Xcode Cloud, and it working when no explicit `type:` is provided.

**Comment by smadsenjc** [comment] 2022-08-26 16:19
@kylebrowning I noticed that the `develop` branch and the 1.12.0-beta2 tag have changes to `Package.swift` that remove the explicit `.dynamic` designation from the `Datadog` product. Switching to the beta and pointing at that library name works in Xcode Cloud.

**Comment by ncreated** [comment] 2022-08-26 16:20
Hello 👋. Thanks for update folks. Speaking of SwiftUI previews, this was recently fixed in https://github.com/DataDog/dd-sdk-ios/pull/949 and the [`Package.swift`](https://github.com/DataDog/dd-sdk-ios/blob/1.12.0-beta2/Package.swift) we now declare in [`1.12.0-beta2`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.12.0-beta2) lets Xcode to infer the type it needs for `Datadog` and `DatadogCrashReporting`.

> What is the history behind explicitly offering both dynamic and static versions of the library, versus letting SPM and the build system handle it?

I feel it is a legacy after we added multiple patches to our SPM support. I gave some more context in [this comment](https://github.com/DataDog/dd-sdk-ios/pull/949#pullrequestreview-1058394659).

Until we make `1.12.0` GA, could someone 🙏 validate if [`1.12.0-beta2`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.12.0-beta2) fixes the issue?

**Comment by kylebrowning** [comment] 2022-08-26 16:20
Wow look at that timing haha

**Comment by El-Fitz** [comment] 2022-09-13 17:29
> Hello 👋. Thanks for update folks. Speaking of SwiftUI previews, this was recently fixed in #949 and the [`Package.swift`](https://github.com/DataDog/dd-sdk-ios/blob/1.12.0-beta2/Package.swift) we now declare in [`1.12.0-beta2`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.12.0-beta2) lets Xcode to infer the type it needs for `Datadog` and `DatadogCrashReporting`.
> 
> > What is the history behind explicitly offering both dynamic and static versions of the library, versus letting SPM and the build system handle it?
> 
> I feel it is a legacy after we added multiple patches to our SPM support. I gave some more context in [this comment](https://github.com/DataDog/dd-sdk-ios/pull/949#pullrequestreview-1058394659).
> 
> Until we make `1.12.0` GA, could someone 🙏 validate if [`1.12.0-beta2`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.12.0-beta2) fixes the issue?

In my case, it did. Funny enough, it was also my first day setting up Datadog in my Swift project.
Quite.a funny coincidence.

**Comment by mleavy** [comment] 2022-09-13 20:21
@El-Fitz I can verify that with releases prior to `1.12.0-betaX` I had the same bundle identifier mismatch issue when building with Xcode Cloud, and that after switching to `1.12.0.beta2`, that build error no longer exists and I can successfully build my project in Xcode Cloud

**Comment by Kaspik** [comment] 2022-09-14 07:40
Thanks for the new betas @ncreated ! Do you have any ETA when the 1.12.0 will be out? :)

**Comment by ncreated** [comment] 2022-09-19 13:35
[`1.12.0` is out](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.12.0) 🙂. Thank you for feedback everyone! I'm closing this issue.

**Closed by ncreated** 2022-09-19 13:35 UTC
Labels: awaiting response, compilation issue
