### ISSUE TITLE
Shipping xcframework with multiple dependency manager

### ISSUE THREAD

**Issue by mnabulsi92** [DataDog/dd-sdk-ios#1438] opened 2023-08-25 11:09 UTC
### The issue

We have a `CustomFramework` where we support integration using cocoapods, carthage and SPM and we want to integrate Datadog v2.

In cocoapods and carthage we don't have any issues but in SPM we are getting this run time error:

`Library not loaded: @rpath/DatadogRUM.framework/DatadogRUM`

We add DataDog frameworks to the `Frameworks and libraries` with `Do not embed` option 
![Screenshot 2023-08-25 at 13 02 30](https://github.com/DataDog/dd-sdk-ios/assets/111436418/94e97e54-4fc8-456a-bad8-d3047a56252b)

Our Packge.swift file

```
let package = Package(
    name: "CustomFramework",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v11)
    ],
    products: [
        .library(
            name: "CustomFramework",
            targets: ["CustomFrameworkBundle"]
        ),
    ],
    dependencies: [
        .package(
            name: "Datadog",
            url: "https://github.com/Datadog/dd-sdk-ios.git",
            .upToNextMajor(from: "2.0.0")
        )
    ],
    targets: [
        .target(name: "CustomFrameworkBundle",
                dependencies: [
                    "CustomFramework",
                    .product(name: "DatadogCore", package: "Datadog"),
                    .product(name: "DatadogRUM", package: "Datadog")
                ]
        ),
        .binaryTarget(
            name: "CustomFrameworkBundle",
            path: "CustomFrameworkBundle.xcframework.zip"
        ),
    ]
)
```

---

#### Datadog SDK version:

2.1.1

#### Last working Datadog SDK version:

We didn't have SPM support before

#### Dependency Manager:

SPM

#### Xcode version:

Xcode 14.3.1

#### Swift version:

5.8.1

#### Deployment Target:

`iOS 11`, `iPhone`

**Comment by ncreated** [comment] 2023-08-25 15:15
Hey @mnabulsi92 👋. This issue is similar to #1402 and it looks you're experiencing the SPM limitations explained in https://github.com/DataDog/dd-sdk-ios/issues/1402#issuecomment-1686349230. We recommend using the workaround discovered by @akovalov (🍺) in there: https://github.com/DataDog/dd-sdk-ios/issues/1402#issuecomment-1680370942.

**Comment by ncreated** [comment] 2023-08-25 16:23
@mnabulsi92 So, we must better understand the setup that leads to this error, so we can reproduce it our side to have a closer look. Could you please describe the minimal example of your configuration?

**Comment by akovalov** [comment] 2023-08-25 16:27
@mnabulsi92 have you tried to add `type: .dynamic` into your `.library(`? [Apple ref](https://developer.apple.com/documentation/packagedescription/product/library/librarytype)

**Comment by mnabulsi92** [comment] 2023-08-25 17:02
> @mnabulsi92 So, we must better understand the setup that leads to this error, so we can reproduce it our side to have a closer look. Could you please describe the minimal example of your configuration?

We have our SDK where we link the DataDog frameworks as `xcframework` in `Frameworks and libraries` but we don't embed them when generating our `xcframework`, and we use `xcodebuild` command to generate the `xcframework`.
The `package.swift` file as provided above.

Not sure if this answers your question, If not can you please let me know which configuration you are referring to exactly.

**Comment by mnabulsi92** [comment] 2023-08-25 17:05
> @mnabulsi92 have you tried to add `type: .dynamic` into your `.library(`? [Apple ref](https://developer.apple.com/documentation/packagedescription/product/library/librarytype)

No i didn't, i will try it.

but i think this refers to how the `. library` should be delivered or how SPM should generate it but we ship the SDK as binary so it's already `dynamic`, i will try it anyway.

Thanks.

**Comment by mnabulsi92** [comment] 2023-08-29 14:08
Hi @ncreated, any updates? any more info required from my side ?

**Comment by ncreated** [comment] 2023-08-29 14:51
Hey @mnabulsi92 👋. Sorry for delay and thanks for describing the framework setup. I more wonder on when is the `Library not loaded: @rpath/DatadogRUM.framework/DatadogRUM` error emitted? Does it come from an example project that you test your framework in? If so, what are the XCFrameworks you integrate into this example project?

**Comment by mnabulsi92** [comment] 2023-08-29 14:58
Hi @ncreated, yes its from an example app that imports our framework using SPM and our framework depends on Datadog as it shows in the provided package.swift file.
So the Error gets emitted from our SDK because we expect that there will be Datadog xcframeworks.
Our SDK link the Framework but does not embed it so at run time we get this error.

**Comment by ncreated** [comment] 2023-08-30 09:30
@mnabulsi92 Sadly, it seems you're struggling SPM limitations and this is not something we can solve in our SDK. The problem occurs after integrating your `CustomFramework` framework to an example app, not when integrating our SDK into your package.

Please see this open proposal in SPM repo: https://github.com/apple/swift-package-manager/issues/4449 as it explains the limited constraints of dependencies in binary frameworks like yours. We also found this community thread where possible workarounds are mentioned: https://forums.swift.org/t/swiftpm-binary-target-with-sub-dependencies/40197. Unfortunately, there seems to be no good & first-class solution at this moment.

I'll close this thread for now as there isn't anything actionable for us. Feel free to start another one if there is anything we can do that could help you.

**Closed by ncreated** 2023-08-30 09:30 UTC
Labels: compilation issue
