### ISSUE TITLE
No logs with the v2.7.0

### ISSUE THREAD

**Issue by floriangbh** [DataDog/dd-sdk-ios#1805] opened 2024-04-30 07:04 UTC
### Describe the bug

Since the v2.7.0 nothing has appeared in my console, but logs appear well in the Datadog dashboard. 
If I downgrade to 2.6.0 everything is ok.

### Reproduction steps

```swift
init() {
        let env = areInRelease ? "production" : "debug"
        
        Datadog.initialize(
            with: Datadog.Configuration(
                clientToken: "****",
                env: env,
                site: .eu1,
                service: Bundle.main.displayName ?? "Unknown"
            ),
            trackingConsent: .granted
        )
        Datadog.verbosityLevel = .debug
        DatadogLogs.Logs.enable()
        
        self.logger = Logger.create(
            with: Logger.Configuration(
                name: Bundle.main.displayName ?? "Unknown",
                networkInfoEnabled: true,
                remoteLogThreshold: .info,
                consoleLogFormat: .shortWith(prefix: "[\(Bundle.main.displayName ?? "")] ")
            )
        )
    }
``` 

### Expected behavior

See the SDK logs in my Xcode console.

### Affected SDK versions

2.7.0

### Latest working SDK version

2.6.0

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Integration Methods

SPM

### Xcode Version

15.3

### Other relevant information

Maybe I missed something about the privacy manifest and ATT ?

**Comment by ganeshnj** [comment] 2024-04-30 08:28
I quickly tested on 2.7.0 and it seems to work fine.

We need more context around the setup, do you have a sample app that we can use to reproduce the issue?

**Comment by floriangbh** [comment] 2024-05-01 12:36
I can make a sample, but if it works on your end, that will work too.
There must be a conflict with something else in my project which appears since version 2.7.0.

If it helps, I got this message since Xcode 15.3:
```
Logging Error: Failed to initialize logging system. Log messages may be missing. If this issue persists, try setting IDEPreferLogStreaming=YES in the active scheme actions environment
```

I will investigate it when I have some time!

**Comment by ganeshnj** [comment] 2024-05-03 12:01
Thanks @floriangbh 

Since there is no action required on our side, closing this issue for now. Feel free to re-open if you encounter an issue.

**Closed by ganeshnj** 2024-05-03 12:01 UTC
Labels: bug, awaiting response

**Comment by floriangbh** [comment] 2024-05-15 13:51
I didn't investigate more at this time!

**Comment by euri21** [comment] 2024-05-28 12:26
Is there any update?

**Comment by saadaamir** [comment] 2024-11-20 10:34
I am having the same issue

**Comment by maxep** [comment] 2024-11-20 12:46
Hello 👋 

We have not identified any issue with the logger and the console. Feel free to share a sample project that reproduce your issue, preferably in another ticket.

Thank you!
