### ISSUE TITLE
BUG: Can't connect (native) resource type with (Xhr) resource type for the same call

### ISSUE THREAD

**Issue by SandraGeorge19** [DataDog/dd-sdk-ios#1297] opened 2023-05-31 15:12 UTC
Thanks for taking the time for reporting an issue!

###The issue
we need to link the traces with the resources that we sent as shown in the screens the traces is sent empty so we did a work around to send the traces in a native resource type in session obj using "Global.rum.startResourceLoading" method but we need a way to link them together or send traces with resources.

Steps to reproduce the issue:
start resource and send custom attributes with it using "Global.rum.startResourceLoading" method and then stop resources using "stopResourceLoading" method with the same attributes
<img width="1211" alt="Screenshot 2023-05-31 at 4 26 54 PM" src="https://github.com/DataDog/dd-sdk-ios/assets/50073317/0eada8b6-ea4d-41f4-992d-d9afc980129d">

Attributes are sent normally but the Traces for that call not sent
<img width="1206" alt="Screenshot 2023-05-31 at 4 26 37 PM" src="https://github.com/DataDog/dd-sdk-ios/assets/50073317/059c1b48-8080-4d89-bbbe-b1fe93fcea95">

### Datadog SDK version:
'DatadogSDK', '1.8.0'

### Last working Datadog SDK version:
'DatadogSDK', '1.8.0'

### Dependency Manager:
Cocoapods

### Xcode version:
Xcode 14.2 (14C18)

### Swift version:
5.0

### Deployment Target:
iOS 12

### macOS version:
macOS Ventura 13.2.1

**Comment by ganeshnj** [comment] 2023-06-01 07:25
Duplicate of https://github.com/DataDog/dd-sdk-ios/issues/1296

Closing.

**Closed by ganeshnj** 2023-06-01 07:25 UTC
